ARG BASE_IMAGE=alpine:latest
FROM ${BASE_IMAGE}

ARG TARGETPLATFORM
ENV TZ=Asia/Shanghai

RUN apk add --no-cache ca-certificates su-exec tzdata && \
    ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo Asia/Shanghai > /etc/timezone && \
    mkdir -p /app

COPY build/docker/${TARGETPLATFORM}/octopus /app/octopus
COPY scripts/dockerfiles/entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

CMD ["/entrypoint.sh"]
